package dev.iseif.listingquality.enrichment.service.book.exception;

public enum BookEnrichmentValidationFailure {
  UNCLASSIFIED,
  STRUCTURE_INVALID,
  DUPLICATE_FIELD,
  DESCRIPTION_POLICY_VIOLATION,
  CONFLICT_INVALID,
  ISBN_INVALID,
  GENERATED_VALUE_INVALID,
  EVIDENCE_MISSING,
  EVIDENCE_REFERENCE_INVALID,
  EVIDENCE_FIELD_NOT_ALLOWED,
  EVIDENCE_VALUE_MISMATCH,
  DERIVED_VALUE_INVALID,
  SHORT_SUMMARY_DESCRIPTION_EVIDENCE_MISSING,
  AGE_RANGE_INVALID
}
