package dev.iseif.listingquality.enrichment.service.shoe;

public enum ShoeColorValidationFailure {
  OUTCOME_INCONSISTENT,
  PRIMARY_COUNT_INVALID,
  TOO_MANY_ADDITIONAL_COLORS,
  DUPLICATE_COLOR,
  EVIDENCE_MISSING,
  EVIDENCE_REFERENCE_INVALID,
  IGNORED_IMAGE_USED_AS_EVIDENCE,
  IMAGE_ASSESSMENT_MISSING,
  IMAGE_ASSESSMENT_DUPLICATED,
  IMAGE_ASSESSMENT_REFERENCE_INVALID
}
